esphome:
  name: livingroom
  build_path: ./builds/livingroom
  platform: esp8266
  board: nodemcuv2
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
logger:
 
api:
  password: !secret api_password
 
ota:
  password: !secret ota_password
 
web_server:
  port: 80


#Wifi info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Wifi SSID

# Restart the device
switch:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    id: button01
    on_press:
      then:
        - light.toggle: light01
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    id: button02
    on_press:
      then:
        - light.toggle: relay01

output:
  - platform: gpio
    pin: D0
    id: output01
    inverted: True

  - platform: gpio
    pin: D6
    id: output02
    inverted: True

light:
  - platform: binary
    name: "My Light"
    id: light01
    output: output01

  - platform: binary
    name: "Relay"
    id: relay01
    output: output02

time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Kolkata
    servers: 0.pool.ntp.org
sensor:
  - platform: adc
    pin: A0
    name: "Living Room Brightness"
    id: ldr01
    update_interval: 60s
 
  - platform: adc
    pin: VCC
    name: "VCC Voltage"
