esphome:
  name: kitchen
  build_path: ./builds/kitchen
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
 
api:
  password: !secret api_password
 
ota:
  password: !secret ota_password

web_server:
  port: 80

#Wifi info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Wifi SSID


